#!/usr/bin/env bash
# configures haproxy on a new server

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  http
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 194879-web-01 54.237.84.19:80 check
        server 194879-web-02 35.175.130.93:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
