#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if
i=0
while [ $i -le 9 ]
do
    echo "Best School"
    if [ $i -eq 8 ]
    then
        echo "Hi"
    fi
    ((i++))
done
